version: '3.5'
services:
    nginx:
        image: nginx:alpine
        container_name: finance-nginx
        working_dir: /var/www/finance
        volumes:
            - ./:/var/www/finance
            - ./.docker/nginx/finance.conf:/etc/nginx/conf.d/default.conf

        links:
            - php
        depends_on:
            - php
        ports:
            - 80:80

    php:
        container_name: finance-php
        build:
            context: .docker/php
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www/finance
            - ./.docker/php/php.ini:/usr/local/etc/php/conf.d/z-php.ini
        working_dir: /var/www/finance
        ports:
            - 9000:9000
volumes:
    redis:
        external: true
